name: Sync Nightly Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # 每天晚上 24:00 (UTC 时间) 执行
  workflow_dispatch:  # 支持通过 URL 手动触发

jobs:

  build:

    env:
      OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
      OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      OSS_BUCKET_NAME: jellyfin-mirror
      OSS_ENDPOINT: oss-cn-wuhan-lr

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (latest)
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'  # 使用最新的 Node.js 版本

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run sync script
      run: pnpm run sync
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated sync commit"
        git push origin master
