name: Sync Nightly Workflow

on:
  schedule:
    - cron: '0 16 * * *'  # 每天晚上 24:00 (UTC+8 北京时间) 执行
  workflow_dispatch:  # 支持通过 URL 手动触发

jobs:

  build:

    env:
      OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
      OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      BAIDU_TRANSLATE_APPID: ${{ secrets.BAIDU_TRANSLATE_APPID }}
      BAIDU_TRANSLATE_SECRET: ${{ secrets.BAIDU_TRANSLATE_SECRET }}
      OSS_BUCKET_NAME: jellyfin-mirror
      OSS_ENDPOINT: oss-cn-wuhan-lr

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (latest)
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'  # 使用最新的 Node.js 版本

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run sync script
      run: pnpm run sync

    - name: 查看生成的文件内容
      run: |
        echo "==== docs/status.md ===="
        cat docs/status.md

    - name: 查看生成的文件内容
      run: |
        echo "==== docs/get-started.md ===="
        cat docs/get-started.md

    # 生成文档
    - name: Build Docs
      run: pnpm run docs:build

    # 部署到 GitHub Pages
    - name: Deploy Docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vitepress/dist
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "action: automated sync commit"
        git push origin master
